swagger: "2.0"
info:
  version: "0.0.1"
  title: LOC-DB Central Component
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
tags:
  - name: BibliographicResource
    description: Services related to bibliographic resources.
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /bibliographicResources:
    # binds a127 app logic to a route
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Returns a list of bibliographic resources
      # used as the method name of the controller
      operationId: list
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            type: array
            items: 
              $ref: "#/definitions/BibliographicResource"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /bibliographicResource/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Returns a single bibliographic resource by id
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: id
          in: path
          description: The internal identifier of the bibliographic resource
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BibliographicResource"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /createBibliographicResourceByPPN:
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Get bibliographic resource by PICA-Prod-Nr.
      operationId: createByPPN
      parameters:
        - name: ppn
          in: query
          description: The PICA-Prod-Nr. assigned by SWB
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BibliographicResource"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  BibliographicResource:
    required:
      - _id
    properties:
      _id:
        type: string
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      type:
        type: string
      title:
        type: string
      subtitle:
        type: string
      edition:
        type: string
      number:
        type: number
      contributors:
        type: array
        items:
          $ref: "#/definitions/AgentRole"
      publicationYear:
        type: number
      parts:
        type: array
        items:
          $ref: "#/definitions/BibliographicEntry"
      partOf:
        type: string
      cites:
        type: array
        items:
          type: string
      embodiedAs:
        type: array
        items:
          $ref: "#/definitions/ResourceEmbodiment"
  
  Identifier:
    required:
      - value
      - scheme
    properties:
      value:
        type: string
      scheme:
        type: string
        
  AgentRole:
    required:
      - roleType
    properties:
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      roleType:
        type: string
      heldBy:
        $ref: "#/definitions/ResponsibleAgent"
        
  ResponsibleAgent:
    required:
      - nameString
    properties:
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      nameString:
        type: string
      givenName:
        type: string
      familyName:
        type: string
  
  ResourceEmbodiment:
    required:
      - type
    properties:
      type:
        type: string
      format:
        type: string
      firstPage:
        type: number
      lastPage:
        type: number
      url:
        type: string
        
  BibliographicEntry:
    required:
      - bibliographicEntryText
    properties:
      bibliographicEntryText:
        type: string
      references:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
