swagger: "2.0"
info:
  version: "0.0.1"
  title: LOC-DB Central Component
host: localhost
basePath: /
tags:
  - name: User
    description: Services related to user management.
  - name: BibliographicResource
    description: Services related to bibliographic resources.
  - name: Scan
    description: Services related to scans.
  - name: BibliographicEntry
    description: Services related to bibliographic entries.
schemes:
  - http
  - https
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
  - image/png
securityDefinitions:
  basicAuth:
    type: basic
  login:
    type: basic

# To apply Basic auth to the whole API:
security:
  - basicAuth: []


paths:
  /login:
    x-swagger-router-controller: user
    post:
      tags: [User]
      description: Login service
      operationId: login
      security:
        - login: []
      parameters:
        - name: user
          in: body
          description: The user object consisting of username and password
          required: true
          schema:
              $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
              $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /signup:
    x-swagger-router-controller: user
    post:
      tags: [User]
      description: Signup service
      operationId: signup
      security: []
      parameters:
        - name: user
          in: body
          description: The user object consisting of username and password
          required: true
          schema:
              $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
              $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /bibliographicResources:
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Returns a list of bibliographic resources
      operationId: list
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags: [BibliographicResource]
      description: Deletes all (!) bibliographic resources (may be removed in a later stage)
      operationId: deleteAll
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags: [BibliographicResource]
      description: Saves a new bibliographic resource into the database
      operationId: save
      parameters:
        - name: bibliographicResource
          in: body
          description: A bibliographic resource to be saved in the database
          required: true
          schema:
            $ref: "#/definitions/BibliographicResource"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /bibliographicEntries/{id}:
    x-swagger-router-controller: bibliographicEntry
    put:
      tags: [BibliographicEntry]
      description: Updates a given bibliographic entry by id. Note that the status needs to be changed to VALID if this service is called after validation by a librarian. Properties that are not given with the update data are preserved.
      operationId: update
      parameters:
        - name: id
          in: path
          description: The _id of the bibliographic entry to be updated.
          required: true
          type: string
        - name: bibliographicEntry
          in: body
          description: A bibliographic entry with new values to be updated.
          required: true
          schema:
            $ref: "#/definitions/BibliographicEntry"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /bibliographicResources/{id}:
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Returns a single bibliographic resource by id
      operationId: get
      parameters:
        - name: id
          in: path
          description: The internal identifier of the bibliographic resource
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags: [BibliographicResource]
      description: Deletes a single bibliographic resource by id
      operationId: deleteSingle
      parameters:
        - name: id
          in: path
          description: The internal identifier of the bibliographic resource
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags: [BibliographicResource]
      description: Updates an existing bibliographic resource
      operationId: update
      parameters:
        - name: id
          in: path
          description: The _id of the bibliographic resource to be updated.
          required: true
          type: string
        - name: bibliographicResource
          in: body
          description: A bibliographic resource to be updated
          required: true
          schema:
            $ref: "#/definitions/BibliographicResource"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /saveScan:
    x-swagger-router-controller: scan
    post:
      tags: [Scan]
      description: Saves a scan in the file system and retrieves a biliographic ressource from SWB-BSZ by PICA-Prod-Nr.The br is saved in the DB.
      operationId: saveScan
      parameters:
        - name: ppn
          in: formData
          description: The PICA-Prod-Nr. assigned by SWB
          required: true
          type: string
        - name: firstPage
          in: formData
          description: The number of the first page of the resource.
          required: true
          type: number
        - name: lastPage
          in: formData
          description: The number of the last page of the resource.
          required: true
          type: number
        - name: scan
          in: formData
          description: The scanned image of the reference page (binary file)
          required: true
          type: file
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /getToDo:
    x-swagger-router-controller: scan
    get:
      tags: [Scan]
      description: Retrieves the BRs including their associated parts and scans that are either not processed or processed by the OCR-component.
      operationId: getToDo
      parameters:
        - name: status
          in: query
          description: The status for which the ToDo-list shall be retrieved
          required: true
          type: string
          enum:
            - NOT_OCR_PROCESSED
            - OCR_PROCESSED
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/ToDo"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /scans/{id}:
    x-swagger-router-controller: scan
    get:
      tags: [Scan]
      description: Returns a single scan by id
      operationId: get
      parameters:
        - name: id
          in: path
          description: The internal identifier of the scan
          required: true
          type: string
      responses:
        200:
          description: Returns Scan
          schema: 
            type: file
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /triggerOcrProcessing:
    x-swagger-router-controller: scan
    get:
      tags: [Scan]
      description: Send a processing request to the OCR component.
      parameters:
        - name: id
          in: query
          description: The unique id of the scan which should be send to the OCR component
          required: true
          type: string
      operationId: triggerOcrProcessing
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /createBibliographicResourceByPPN:
    x-swagger-router-controller: bibliographicResource
    get:
      tags: [BibliographicResource]
      description: Get bibliographic resource by PICA-Prod-Nr.
      operationId: createByPPN
      parameters:
        - name: ppn
          in: query
          description: The PICA-Prod-Nr. assigned by SWB
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /getToDoBibliographicEntries:
    x-swagger-router-controller: bibliographicEntry
    get:
      tags: [BibliographicEntry]
      description: Retrieves the BEs that are not processed by a librarian yet.
      operationId: getToDoBibliographicEntries
      parameters:
        - name: scanId
          in: query
          description: The Id of the Scan for which the BEs shall be retrieved
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/BibliographicEntry"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /getInternalSuggestions:
    x-swagger-router-controller: bibliographicEntry
    post:
      tags: [BibliographicEntry]
      description: Retrieves internal br suggestions for a given (probably messy) be.
      operationId: getInternalSuggestions
      parameters:
        - name: bibliographicEntry
          in: body
          description: The be for which the suggestions shall be retrieved
          required: true
          schema:
            $ref: "#/definitions/BibliographicEntry"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /getExternalSuggestions:
    x-swagger-router-controller: bibliographicEntry
    post:
      tags: [BibliographicEntry]
      description: Retrieves external br suggestions for a given (probably messy) be.
      operationId: getExternalSuggestions
      parameters:
        - name: bibliographicEntry
          in: body
          description: The be for which the suggestions shall be retrieved
          required: true
          schema:
            $ref: "#/definitions/BibliographicEntry"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/BibliographicResource"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw



definitions:

  BibliographicResource:
    properties:
      _id:
        type: string
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      type:
        type: string
      title:
        type: string
      subtitle:
        type: string
      edition:
        type: string
      number:
        type: number
      contributors:
        type: array
        items:
          $ref: "#/definitions/AgentRole"
      publicationYear:
        type: number
      status:
        type: string
      parts:
        type: array
        items:
          $ref: "#/definitions/BibliographicEntry"
      partOf:
        type: string
      embodiedAs:
        type: array
        items:
          $ref: "#/definitions/ResourceEmbodiment"
  
  Identifier:
    required:
      - literalValue
      - scheme
    properties:
      literalValue:
        type: string
      scheme:
        type: string
        
  AgentRole:
    required:
      - roleType
    properties:
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      roleType:
        type: string
      heldBy:
        $ref: "#/definitions/ResponsibleAgent"
        
  ResponsibleAgent:
    properties:
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      nameString:
        type: string
      givenName:
        type: string
      familyName:
        type: string
  
  ResourceEmbodiment:
    properties:
      type:
        type: string
      format:
        type: string
      firstPage:
        type: number
      lastPage:
        type: number
      url:
        type: string
      scans:
        type: array
        items:
          $ref: "#/definitions/ToDoParts"

#  Scan:
#    required:
#      - scanName
#    properties:
#      scanName:
#        type: string
#      xmlName:
#        type: string
#      status:
#        type: string

  BibliographicEntry:
    properties:
      _id:
        type: string
      bibliographicEntryText:
        type: string
      references:
        type: string
      scanId:
        type: string
      status:
        type: string
      ocrData:
        $ref: "#/definitions/OCRData"


  OCRData:
    properties:
      coordinates:
        type: string
      authors:
        type: array
        items:
          type: string
      title:
        type: string
      date:
        type: string
      marker:
        type: string
      comments:
        type: string

  ToDo:
    required:
      - _id
    properties:
      _id:
        type: string
      identifiers:
        type: array
        items:
          $ref: "#/definitions/Identifier"
      type:
        type: string
      title:
        type: string
      subtitle:
        type: string
      edition:
        type: string
      number:
        type: number
      contributors:
        type: array
        items:
          $ref: "#/definitions/AgentRole"
      publicationYear:
        type: number
      children:
        type: array
        items:
          $ref: "#/definitions/ToDoParts"

  ToDoParts:
    required:
      - _id
    properties:
      _id:
        type: string
      status:
        type: string
      scans:
        type: array
        items:
          $ref: "#/definitions/ToDoScans"

  ToDoScans:
    required:
      - _id
    properties:
      _id:
        type: string
      status:
        type: string

  User:
    properties:
      username:
        type: string
      password:
        type: string

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
